services:
  - type: web
    name: rcd-website
    runtime: static
    repo: https://github.com/NeVoTM/rcd-website
    branch: main
    autoDeploy: true
    buildCommand: echo "Static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /clip
        destination: /clip.html
